import Head from "next/head";

import Shopify from "@shopify/shopify-api";
import Hero from "../components/Hero";
import { shop, storefrontAccessToken } from "../endpoints";
import { productsQuery } from "../src/queries/products";
import Products from "../components/Products/Products";

export async function getStaticProps() {
  const storefrontClient = new Shopify.Clients.Storefront(shop, storefrontAccessToken);

  const { body } = await storefrontClient.query(productsQuery);
  return {
    props: {
      products: body.data.products.edges,
    },
  };
}

export default function Home({ products }) {
  console.log(products);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero products={products} />
      <Products products={products} />
    </>
  );
}
