import { gql } from "@apollo/client";
import client from "../apollo-client";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Shopify from "@shopify/shopify-api";
import Hero from "../components/Hero";
import { shop, storefrontAccessToken } from "../endpoints";
import { productsQuery, threeProducts } from "../src/queries/products";
import Products from "../components/Products/Products";
// import storefront from "../shopify";
// import { storefrontClient } from "../shopify";

export async function getStaticProps() {
  const storefrontClient = new Shopify.Clients.Storefront(shop, storefrontAccessToken);

  const { body } = await storefrontClient.query(productsQuery);
  // const queryProduct = `{
  //   products (first: 3) {
  //   edges {
  //       node {
  //        id
  //         title
  //     }
  //    }
  //    }
  //  }`;
  // const products = await storefront(queryProduct);
  // const allProducts = JSON.parse(JSON.stringify(products));
  return {
    props: {
      products: body.data.products.edges,
    },
  };
}

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero products={products} />
      <Products products={products} />
    </>
  );
}
